export const CHEESE_PUNS = [
  "Curd Cobain",
  "Brie Larson",
  "Gouda Buddha",
  "Feta WAP",
  "Cheddar Bob",
  "Mozzarella Fitz",
  "Parmesan Sean",
  "Ricotta Ross",
  "Swiss Miss",
  "Gorgonzola Zola",
  "Havarti Party",
  "Provolone Malone",
  "Muenster Mash",
  "Camembert Bear",
  "Roquefort Fort",
  "Asiago Ago",
  "Manchego Ego",
  "Pepper Jack",
  "Colby Jack",
  "Monterey Jack",
  "String Cheese",
  "Kraft Punk",
  "Velveeta",
  "Chez Whiz",
  "Nacho Libre",
  "Queso Blanco",
  "Fondue Hue",
  "Raclette Racket",
  "Burrata Bata",
  "Halloumi Homie",
  "Paneer Near",
  "Mascarpone Pony",
  "Cotija Mija",
  "Limburger Burger",
  "Emmental Mental",
  "Gruyere Grin",
  "Edam Dame",
  "Stilton Stilt",
  "Taleggio Leggio",
  "Pecorino Rino",
  "Fontina Tina",
  "Jarlsberg Burg",
  "Danbo Dumbo",
  "Tilsit Sit",
  "Cantalsal",
  "Mimolette Mimo"
];

export const getRandomPun = () => {
    return CHEESE_PUNS[Math.floor(Math.random() * CHEESE_PUNS.length)];
};
